config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#show'
  resources :users, only: :show
  resources :posts, only: :index
  resources :meetings do
    resources :comments, only: [:create, :destroy,]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  validates :text, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :content, presence: true
  validates :attack,  presence: true
  validates :defence, presence: true
  validates :attack_url, presence: true
  validates :defence_url, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :meetings
    has_many :comments, dependent: :destroy

    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX
    
    validates :name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥々ー]+\z/, massage: "名前を入れてください" }
    validates :team_name, presence: true
    validates :number, presence: true, format: { with: /\A[0-9]+\z/, massage: "背番号を入れてください" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :team_name, :number])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2939'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to meeting_path(@comment.meeting)
    else
      @meeting = @comment.meeting
      @comments = @meeting.comments
      render "meetings/show"
    end
  end

  def destroy
    @meeting = Meeting.find(params[:meeting_id])
    @comment = Comment.find(params[:id])
     if user_signed_in? && @comment.user_id == current_user.id
       @comment.destroy
       redirect_to root_path
      else
        redirect_to posts_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, meeting_id: params[:meeting_id])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :show, :edit] 
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = Meeting.includes(:user).order("created_at ASC")
  end

  def new 
    @meeting = Meeting.new
    @meeting = current_user.meetings.build
  end

  def create
    @meeting = Meeting.create(meeting_params)
    if @meeting.save
       redirect_to meetings_path
    else
      render "new"
    end
  end

  def show
    @comment = Comment.new
    @comments = @meeting.comments
  end

  def edit
  end

  def update
    if @meeting.update(meeting_params)
      redirect_to meetings_path
    else
      render 'edit'
    end
  end

  def destroy
    if @meeting.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end



  private
  def meeting_params
    params.require(:meeting).permit(:content, :attack, :defence, :attack_url, :defence_url).merge(user_id: current_user.id)
  end

  def set_tweet
    @meeting = Meeting.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>deporta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("deportalogo.png", class: :logo), root_path %>
          </div>
          <div class="navbar">
            <% if user_signed_in? %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "一覧ページへ", posts_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © DEPORTA! All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with model: @meeting,  local: true do |f|%>
  <div class="field">
    <%= f.label :content, "共有事項" %><br />
    <%= f.text_area :content, class: :form__text, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :attack, "攻撃面について" %><br />
    <%= f.text_area :attack, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :defence, "守備面について" %><br />
    <%= f.text_area :defence, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :attack_url, "攻撃動画について" %><br />
    <%= f.text_area :attack_url, class: :form__text, id:"prototype_image" %>
  </div>

  <div class="field">
    <%= f.label :defence_url, "守備動画について" %><br />
    <%= f.text_area :defence_url, class: :form__text, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/meetings/_meeting.html.erb
<div class="js-tab-panel">
    <div class="flex justify-start">
      <div class="js-tab active_tab">
        共有事項
      </div>
      <div class="js-tab inactive_tab">
        攻撃面について
      </div>
     <div class="js-tab inactive_tab">
       守備面について
     </div>
      <div class="js-tab inactive_tab">
        攻撃動画
      </div>
      <div class="js-tab inactive_tab">
        守備動画
      </div>
    </div>

  <div class="js-panel active_content">
    <%=safe_join(meeting.content.split("\n"),tag(:br))%>
  </div>

  <div class="js-panel inactive_content">
    <%=safe_join(meeting.attack.split("\n"),tag(:br))%>
  </div>

  <div class="js-panel inactive_content">
    <%=safe_join(meeting.defence.split("\n"),tag(:br))%>
  </div>

  <div class="js-panel inactive_content">
    <%= link_to "動画", "#{meeting.attack_url}", method: :get %>
  </div>

  <div class="js-panel inactive_content">
    <%= link_to "動画", "#{meeting.defence_url}", method: :get %>
  </div>

  <ul class="more_list">
    <li>
      <%= link_to '詳細', meeting_path(meeting), method: :get, class: :show__btn %>
    </li>
  </ul>

  <div class="messa-date">
    <a class="submessa-date">投稿日時</a>
    <%= l meeting.created_at %>
    <span> 投稿者：</span><%= meeting.user.name %>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ミーティング内容編集</h2>
      <%= render partial: "form", locals: { meeting: @meeting } %>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="card__wrapper1">
  <%= render partial: 'meeting', collection: @meetings %>
</div>

app/views/meetings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
    <h2 class="page-heading">ミーティング内容</h2>
    <%= form_with model: @meeting, local: true do |f|%>
    <%= link_to "ミーティング一覧ページへ", meetings_path, class: :me_new__btn %>
      <div class="field"> 
        <%= f.label :content, "共有事項" %><br />
        <%= f.text_area :content, class: :form__text %>
      </div>

      <div class="field">
        <%= f.label :attack, "攻撃面について" %><br />
        <%= f.text_area :attack, class: :form__text %>
      </div>

      <div class="field">
        <%= f.label :defence, "守備面について" %><br />
        <%= f.text_area :defence, class: :form__text %>
      </div>

      <div class="field">
        <%= f.label :attack_url, "攻撃動画について(なしの場合は「なし」)" %><br />
        <%= f.text_area :attack_url, class: :form__text %>
      </div>

      <div class="field">
        <%= f.label :defence_url, "守備動画について(なしの場合は[なし」)" %><br />
        <%= f.text_area :defence_url, class: :form__text %>
      </div>

      <div class="actions">
        <%= f.submit "保存する", class: :form__btn  %>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @meeting.content %>
      </p>
      <%= link_to "by #{@meeting.user.name}", root_path, class: :prototype__user %>
          <div class="prototype__manage">
            <%= link_to "編集する", edit_meeting_path(@meeting), class: :prototype__btn %>
            <%= link_to "削除する", meeting_path(@meeting), method: :delete, class: :prototype__btn %>
          </div>

      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">■共有事項</p>
          <p class="detail__message">
            <%=safe_join(@meeting.content.split("\n"),tag(:br))%>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">■攻撃面について</p>
          <p class="detail__message">
            <%=safe_join(@meeting.attack.split("\n"),tag(:br))%>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">■守備面について</p>
          <p class="detail__message">
            <%=safe_join(@meeting.defence.split("\n"),tag(:br))%>
          </p>
      </div>
      <div class="prototype__detail">
          <p class="detail__title">■攻撃動画</p>
          <p class="detail__message">
            <%= link_to "攻撃動画", "#{@meeting.attack_url}", method: :get %>
          </p>
        </div>

        <div class="prototype__detail">
          <p class="detail__title">■守備動画</p>
          <p class="detail__message">
            <%= link_to "守備動画", "#{@meeting.defence_url}", method: :get %>
          </p>
        </div>
      </div>

      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@meeting, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "※コメント漏れで欠席(100m30本)は罰走です" %><br />
              <%= f.text_field :text, id:"comment_content", class: :comment_content %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
          <ul class="comments_lists">
            <% @comments.each do | comment | %>
              <li class="comments_list">
                <%= comment.text %>
                <%= link_to "#{comment.user.name}", user_path(@meeting.user), class: :comment_user %>
              </li>
              <div class="message-date">
                <%= l comment.created_at %>
              </div>
                <%= link_to "削除", meeting_comment_path(@meeting, comment), method: :delete %>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</main>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
     <% if user_signed_in?  %>
      <div class="p-greeting">
        <%= "ようこそ！" %>
        <%= link_to "Let's enjoy sport", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= link_to ("/meetings/new") do %>
        <%= image_tag 'Meeting.png',size: '250x200', class: "purchase-btn-icon" %>
      <% end %>

      <%= link_to ("/prototypes/new") do %>
        <%= image_tag 'status.png',size: '250x200', class: "purchase-btn-icon" %>
      <% end %>
      
      <%= link_to ("/prototypes/new") do %>
        <%= image_tag 'sche.png',size: '250x200', class: "purchase-btn-icon" %>
      <% end %>
    </div>
  </div>
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%=  "#{@user.name}さんの情報" %>
      </h2>
      <table class="table" class: :user_info>
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">所属チーム</th>
            <td class="table__col2"><%= @user.team_name %></td>
          </tr>
          <tr>
            <th class="table__col1">背番号</th>
            <td class="table__col2"><%= @user.number %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>